set-env.sh called on all scripts

diff --git a/templates/default/kill-process.sh.erb b/templates/default/kill-process.sh.erb
--- a/templates/default/kill-process.sh.erb
+++ b/templates/default/kill-process.sh.erb
@@ -11,19 +11,28 @@ COMMAND=$3
 PID_DIR=$4
 res=1
 
+NOT_FOUND=99
+
 function kill_named {
     PID=`ps aux | grep -i $COMMAND | grep $SERVICE | awk '{print $2}'`
     if [ "$PID" != "" ] ; then
 	kill -9 $PID
         res=$?
+    else
+	res=$NOT_FOUND
     fi
+    return $res
 }
 
 echo "Stopping the $COMMAND"
 PID_FILE=$PID_DIR/$SERVICE-$USER_NAME-$COMMAND.pid
-PID=`cat $PID_FILE`
-kill $PID
-res=$?
+
+res=1
+if [ -f $PID_FILE ] ; then
+ PID=`cat $PID_FILE`
+ kill $PID
+ res=$?
+fi
 
 if [ $res -ne 0 ] ; then
     kill_named
@@ -48,6 +57,8 @@ fi
 
 if [ $res -eq 0 ] ; then
  echo "Killed $SERVICE/$COMMAND"
+elif [ $res -eq $NOT_FOUND ] ; then
+    echo "Could not find $SERVICE/$COMMAND to kill"
 fi
 
 exit $res
